#!/bin/bash
# ~/tools/install-bash-wrapper.sh — replace /bin/bash with a wrapper that
# auto-loads the omnibin command_not_found_handle via BASH_ENV.
# This makes `program@version` work in every exec with zero per-exec setup.
# Idempotent. Run on boot via init.sh (overlay wipes /bin/bash).
# The wrapper execs /bin/bash.real (backup of the original binary).
set -u

# If /bin/bash is already our wrapper with the current BASH_ENV target,
# nothing to do.
if head -1 /bin/bash 2>/dev/null | grep -q "bash.real"; then
  if grep -q 'BASH_ENV=/home/hatch/tools/shell-env.sh' /bin/bash 2>/dev/null \
     && [ -x /bin/bash.real ]; then
    exit 0
  fi
  # Wrapper exists but points at an old BASH_ENV target — reinstall below.
fi

# Backup the original binary — BUT ONLY IF /bin/bash is a real binary.
# If /bin/bash is already our wrapper script, /bin/bash.real must be left
# alone (copying the script over it destroys the binary and creates a
# shebang loop — this exact failure happened 2026-09-30 and was recovered
# by restoring bash from the nix store).
if head -1 /bin/bash 2>/dev/null | grep -q "bash.real"; then
  # Already a wrapper: keep the existing bash.real, but verify it's a binary.
  if ! head -c 4 /bin/bash.real 2>/dev/null | grep -q $'\x7fELF'; then
    echo "FATAL: /bin/bash is a wrapper but /bin/bash.real is not an ELF binary; refusing to proceed" >&2
    exit 1
  fi
else
  # Real binary: back it up (may be busy if this script runs under it;
  # the running process keeps the old inode after unlink).
  cp /bin/bash /bin/bash.real 2>/dev/null || {
    # Fallback: if cp fails (e.g. text file busy during copy), try rm+cp.
    rm -f /bin/bash.real
    cp /bin/bash /bin/bash.real
  }
  chmod +x /bin/bash.real
fi

# Install the wrapper atomically: write temp in /bin (same filesystem),
# then rename over /bin/bash. Use mv to handle "text file busy" (running
# bash keeps the old inode).
cat > /bin/.bash-wrapper-new <<'EOF'
#!/bin/bash.real
# Auto-generated by ~/tools/install-bash-wrapper.sh. Do not edit.
# BASH_ENV is inherited across exec and auto-sourced by non-interactive bash,
# defining command_not_found_handle for `program@version` support.
export BASH_ENV=/home/hatch/tools/shell-env.sh
exec /bin/bash.real "$@"
EOF
chmod +x /bin/.bash-wrapper-new
mv -f /bin/.bash-wrapper-new /bin/bash

# Rollback: if the wrapper ever breaks the shell, restore with:
#   cp /bin/bash.real /bin/bash
# (/bin/bash.real is always a real binary; the installer never overwrites
# it when /bin/bash is already a wrapper.)

# Verify.
head -1 /bin/bash | grep -q "bash.real" && [ -x /bin/bash.real ]
