#!/bin/bash
# ~/tools/install-nix-wrapper.sh — put a `nix` wrapper on the default PATH.
# /usr/local/bin is on the default PATH for all shells (interactive or not),
# so this makes `nix` work everywhere with no per-shell LD_PRELOAD/PATH setup.
# The wrapper sets LD_PRELOAD (taint-shim) and execs the USER PROFILE's nix
# binary directly (/nix/var/nix/profiles/per-user/root/profile/bin/nix).
# nix itself is installed there as nixpkgs#nix, so there is exactly one
# profile to maintain. If the profile's nix is missing/not executable, the
# wrapper runs nix-ensure.sh — which self-heals the profile from any nix
# binary left in the store — and retries once; if still broken it fails loud.
# After `nix profile install/remove/upgrade/rollback`, it re-runs
# nix-profile-sync.sh so new binaries land on the PATH automatically.
# Idempotent. Run on boot via init.sh (overlay wipes /usr/local/bin).
set -u
mkdir -p /usr/local/bin
# Atomic install: temp file in the same dir, then rename.
cat > /usr/local/bin/.nix-new <<'EOF'
#!/bin/bash
# Auto-generated by ~/tools/install-nix-wrapper.sh. Do not edit.
export LD_PRELOAD=/home/hatch/tools/taint-shim/taint_shim.so
PROFILE_NIX=/nix/var/nix/profiles/per-user/root/profile/bin/nix
if [ ! -x "$PROFILE_NIX" ]; then
  # Self-heal: reinstall nix into the profile from any nix binary left in
  # the store. Via bash.real (not the /bin/bash wrapper) with BASH_ENV
  # cleared, so the shell sentinel can't re-trigger a redundant repair
  # mid-heal (BASH_ENV is exported and would otherwise be inherited).
  if [ -x /bin/bash.real ]; then
    BASH_ENV= /bin/bash.real /home/hatch/tools/nix-ensure.sh >/dev/null 2>&1 || true
  else
    BASH_ENV= bash /home/hatch/tools/nix-ensure.sh >/dev/null 2>&1 || true
  fi
fi
if [ ! -x "$PROFILE_NIX" ]; then
  echo "nix: profile nix missing at $PROFILE_NIX and self-heal failed" >&2
  exit 1
fi
"$PROFILE_NIX" "$@"
code=$?
if [ "${1:-}" = "profile" ]; then
  case "${2:-}" in
    install|remove|upgrade|rollback)
      bash /home/hatch/tools/nix-profile-sync.sh >/dev/null 2>&1 || true
      ;;
  esac
fi
exit $code
EOF
chmod +x /usr/local/bin/.nix-new
mv -f /usr/local/bin/.nix-new /usr/local/bin/nix
[ -x /usr/local/bin/nix ]
