#!/bin/bash
# ~/tools/install-bash-wrapper.sh — replace /bin/bash with a wrapper that
# auto-loads the omnibin command_not_found_handle via BASH_ENV.
# This makes `program@version` work in every exec with zero per-exec setup.
# Idempotent. Run on boot via init.sh (overlay wipes /bin/bash).
# The wrapper execs /bin/bash.real (backup of the original binary).
set -u

# If /bin/bash is already our wrapper, nothing to do.
if head -1 /bin/bash 2>/dev/null | grep -q "bash.real"; then
  [ -x /bin/bash.real ] && exit 0
fi

# Backup the original binary (may be busy if this script runs under it;
# the running process keeps the old inode after unlink).
cp /bin/bash /bin/bash.real 2>/dev/null || {
  # Fallback: if cp fails (e.g. text file busy during copy), try rm+cp.
  rm -f /bin/bash.real
  cp /bin/bash /bin/bash.real
}
chmod +x /bin/bash.real

# Install the wrapper. Use rm+cp to handle "text file busy" (running bash).
cat > /tmp/bash-wrapper-new <<'EOF'
#!/bin/bash.real
# Auto-generated by ~/tools/install-bash-wrapper.sh. Do not edit.
# BASH_ENV is inherited across exec and auto-sourced by non-interactive bash,
# defining command_not_found_handle for `program@version` support.
export BASH_ENV=/home/hatch/tools/omnibin-not-found.sh
exec /bin/bash.real "$@"
EOF
chmod +x /tmp/bash-wrapper-new
rm -f /bin/bash
cp /tmp/bash-wrapper-new /bin/bash
chmod +x /bin/bash
rm -f /tmp/bash-wrapper-new

# Verify.
head -1 /bin/bash | grep -q "bash.real" && [ -x /bin/bash.real ]
