#!/bin/bash
# ~/tools/install-nix-wrapper.sh — put a `nix` wrapper on the default PATH.
# /usr/local/bin is on the default PATH for all shells (interactive or not),
# so this makes `nix` work everywhere with no per-shell LD_PRELOAD/PATH setup.
# The wrapper sets LD_PRELOAD (taint-shim) and execs the real nix binary.
# After `nix profile install/remove/upgrade/rollback`, it re-runs
# nix-profile-sync.sh so new binaries land on the PATH automatically.
# Idempotent. Run on boot via init.sh (overlay wipes /usr/local/bin).
set -u
mkdir -p /usr/local/bin
cat > /usr/local/bin/nix <<'EOF'
#!/bin/bash
# Auto-generated by ~/tools/install-nix-wrapper.sh. Do not edit.
export LD_PRELOAD=/home/hatch/tools/taint-shim/taint_shim.so
/nix/var/nix/profiles/default/bin/nix "$@"
code=$?
if [ "${1:-}" = "profile" ]; then
  case "${2:-}" in
    install|remove|upgrade|rollback)
      bash /home/hatch/tools/nix-profile-sync.sh >/dev/null 2>&1 || true
      ;;
  esac
fi
exit $code
EOF
chmod +x /usr/local/bin/nix
[ -x /usr/local/bin/nix ]
